# backend/Dockerfile

FROM python:3.12-slim

# Define o diretório de trabalho principal
WORKDIR /app

# Copia apenas o arquivo de dependências
COPY ./requirements.txt .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia o seu pacote de aplicação (a pasta local 'app') para dentro do WORKDIR
# O conteúdo da pasta 'app' local é copiado para a raiz do WORKDIR (/app).
COPY ./app .

# Expõe a porta que o servidor irá usar
EXPOSE 5000

# Configura e inicia o servidor de desenvolvimento do Flask, que é mais adequado
# para o ambiente de desenvolvimento e possui um hot-reloading mais robusto.
ENV FLASK_APP=main:app
ENV FLASK_DEBUG=1

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]