baseURL: "https://unb-mds.github.io/2025-2-NewsHub/"

defaultContentLanguage: en

# URLs
relativeURLs: true
canonifyURLs: true
uglyURLs: false

build:
  buildStats:
    disableClasses: false
    disableIDs: true
    disableTags: false
    enable: true

enableRobotsTXT: true

imaging:
  quality: 75

markup:
  tableOfContents:
    ShowToc: false
    ordered: true

pagination:
  pagerSize: 9

removePathAccents: true
timeout: 100000
